import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { IconsMenu, Header } from "../components";
import RoomsList from "../components/elements/roomsList";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-[100vh] relative">
        <div className="flex w-full flex-col justify-center items-center">
          <div className="w-full sticky top-0 z-50 bg-white shadow">
            <Header/>
            <div className="w-full">
              <div className="w-full items-center flex-row flex 2xl:px-20 px-5 pt-5">
                <div className="w-full overflow-x-auto relative">
                  <div className="w-max space-x-11">
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                  </div>

                  {/* <div className="absolute w-12 flex justify-center items-center bg-gradient-to-l from-white via-white h-full right-0">
                    <div className="w-[28px] mb-5 h-[28px] flex items-center justify-center bg-white border rounded-full">
                      <Image
                        src={"/nav-arrow-right.svg"}
                        width={20}
                        height={20}
                        alt="flet"
                      />
                    </div>
                  </div>

                  <div className="absolute w-12 flex justify-center items-center bg-gradient-to-r from-white h-full left-0">
                    <div className="w-[28px] mb-5 h-[28px] flex items-center justify-center bg-white border rounded-full">
                      <Image
                        src={"/nav-arrow-left.svg"}
                        width={20}
                        height={20}
                        alt="flet"
                      />
                    </div>
                  </div> */}
                </div>
                <div className="hidden lg:block mb-3 ml-5">
                  <div className="flex hover:shadow space-x-2 border px-5 py-3 rounded-xl">
                    <Image
                      src={"/filter.png"}
                      width={20}
                      height={20}
                      alt="flet"
                    />{" "}
                    <span>Filtres</span>
                  </div>
                </div>
              </div>
            </div>
          </div>

      <RoomsList/>
        </div>
        <footer className="w-full hidden lg:block px-20 py-4 bg-white border-t sticky bottom-0 z-50">
          <div className="w-full flex justify-between">
            <div className="text-[14px]">
            <span>© 2022 Airbnb, Inc.</span>
            <span className="mx-3">·</span>
            <Link href={"#"}>Confidentialité</Link>
            <span className="mx-3">·</span>
            <Link href={"#"}>Conditions générales</Link>
            <span className="mx-3">·</span>
            <Link href={"#"}>Plan du site</Link>
            <span className="mx-3">·</span>
            <Link href={"#"}>Fonctionnement du site</Link>
            <span className="mx-3">·</span>
            <Link href={"#"}>Infos sur l entreprise</Link>
            <span className="mx-3">·</span>
            <Link href={"#"}>Destinations</Link>
          </div>
          <div>
            <Link className="font-semibold" href={"#"}>
              Français (FR)
            </Link>
          </div>
          </div>
          
        </footer>
      </main>
    </>
  );
}
