import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Logo, RoomCard, IconsMenu, Header } from "../components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-[100vh] relative">
        <div className="flex w-full flex-col justify-center items-center">
          <div className="w-full sticky top-0 z-50 bg-white shadow">
            <Header />
            <div className="w-full">
              <div className="w-full items-center flex-row flex 2xl:px-20 px-5 pt-5">
                <div className="w-full overflow-x-auto relative">
                  <div className="w-max space-x-11">
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                    <IconsMenu />
                  </div>

                  {/* <div className="absolute w-12 flex justify-center items-center bg-gradient-to-l from-white via-white h-full right-0">
                    <div className="w-[28px] mb-5 h-[28px] flex items-center justify-center bg-white border rounded-full">
                      <Image
                        src={"/nav-arrow-right.svg"}
                        width={20}
                        height={20}
                        alt="flet"
                      />
                    </div>
                  </div>

                  <div className="absolute w-12 flex justify-center items-center bg-gradient-to-r from-white h-full left-0">
                    <div className="w-[28px] mb-5 h-[28px] flex items-center justify-center bg-white border rounded-full">
                      <Image
                        src={"/nav-arrow-left.svg"}
                        width={20}
                        height={20}
                        alt="flet"
                      />
                    </div>
                  </div> */}
                </div>
                <div className="hidden lg:block mb-3 ml-5">
                  <div className="flex hover:shadow space-x-2 border px-5 py-3 rounded-xl">
                    <Image
                      src={"/filter.png"}
                      width={20}
                      height={20}
                      alt="flet"
                    />{" "}
                    <span>Filtres</span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="w-full 2xl:px-20 px-5 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-6 gap-6 mt-4 mb-5">
            <RoomCard image={"/1.webp"} />
            <RoomCard image={"/2.webp"} />
            <RoomCard image={"/4.webp"} />
            <RoomCard image={"/5.webp"} />
            <RoomCard image={"/6.webp"} />
            <RoomCard image={"/7.webp"} />
            <RoomCard image={"/8.webp"} />
            <RoomCard image={"/9.webp"} />
            <RoomCard image={"/10.webp"} />
            <RoomCard image={"/11.webp"} />
            <RoomCard image={"/12.webp"} />
            <RoomCard image={"/14.webp"} />
            <RoomCard />
            <RoomCard />
            <RoomCard />
            <RoomCard />
            <RoomCard />
            <RoomCard />
            <RoomCard />
            <RoomCard />
            <RoomCard />
            <RoomCard />
            <RoomCard />
            <RoomCard />
          </div>
        </div>
        <footer className="w-full flex justify-between px-20 py-4  bg-white border-t sticky bottom-0 z-50">
          <div className="text-[14px]">
            <span>© 2022 Airbnb, Inc.</span>
            <span className="mx-3">·</span>
            <Link href={"#"}>Confidentialité</Link>
            <span className="mx-3">·</span>
            <Link href={"#"}>Conditions générales</Link>
            <span className="mx-3">·</span>
            <Link href={"#"}>Plan du site</Link>
            <span className="mx-3">·</span>
            <Link href={"#"}>Fonctionnement du site</Link>
            <span className="mx-3">·</span>
            <Link href={"#"}>Infos sur l entreprise</Link>
            <span className="mx-3">·</span>
            <Link href={"#"}>Destinations</Link>
          </div>
          <div>
            <Link className="font-semibold" href={"#"}>
              Français (FR)
            </Link>
          </div>
        </footer>
      </main>
    </>
  );
}
